#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ssh_chroot_dir"
name = "ssh chroot directory"
description.en = "SSH chroot directories with quotas disk"
description.fr = "Dossier SSH en chroot avec gestion de quotas"

version = "1.3~ynh3"

maintainers = []

[upstream]
license = "GPL-3.0"
code = "https://github.com/maniackcrudelis/ssh_chroot"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "5M"
ram.build = "0M"
ram.runtime = "0M"

[install]
    [install.ssh_user]
    ask.en = "Choose a new user for this directory"
    ask.fr = "Choisissez un nouvel utilisateur pour ce dossier"
    help.en = "It must be a new user, it will be created for this purpose."
    help.fr = "Ce doit être un nouvel utilisateur, il sera créé pour cet usage."
    type = "string"
    example = "johndoe"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    help.en = "OPTIONAL. It's better to use a public ssh key instead. See below."
    help.fr = "OPTIONNEL. Il est préférable d'utiliser une clé publique. Voir ci-dessous."
    type = "password"
    optional = true

    [install.pub_key]
    ask.en = "Give the public ssh key"
    ask.fr = "Donnez une clé publique ssh"
    help.en = "OPTIONAL. You can use a password instead, but a ssh public key is more secure. Ask to your beneficiary for his public key."
    help.fr = "OPTIONNEL. Vous pouvez utiliser un mot de passe à la place, mais une clé ssh publique est plus sécurisée. Demandez à votre bénéficiaire sa clé publique."
    type = "string"
    optional = true

    [install.size]
    ask.en = "Choose the maximum space allowed to this user"
    ask.fr = "Choississez l'espace maximum à allouer à cet utilisateur"
    help.en = "Default Ko, Use M, G or T to specified another unit."
    help.fr = "Ko par défaut, utilisez M, G ou T pour indiquer une autre unité."
    type = "string"
    default = "10G"

[resources]
    [resources.sources.main]
    url = "https://github.com/maniackcrudelis/ssh_chroot/archive/v1.3.tar.gz"
    sha256 = "d44b51f8d838fc9f929e6048b825c8f74d52f6a254764527bce1ed4a4c558652"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    dir = "/home/yunohost.app/ssh_chroot_directories"

    [resources.permissions]

    [resources.apt]
    packages = ["rsync"]
