#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
ynh_script_progression --message="Retrieve arguments from the manifest" --weight=2

ssh_user=$YNH_APP_ARG_SSH_USER
# Default value is null
ynh_print_OFF; password=${YNH_APP_ARG_PASSWORD:-}; ynh_print_ON
pub_key=${YNH_APP_ARG_PUB_KEY:-}
size=$YNH_APP_ARG_SIZE

app=$YNH_APP_INSTANCE_NAME

#=================================================
# DISCLAIMER
#=================================================

PACKAGE_CHECK_EXEC=${PACKAGE_CHECK_EXEC:-0}
if [ "$PACKAGE_CHECK_EXEC" != "0" ]; then
	ynh_print_warn "This app can't be tested by package check. Please see the readme for more information. https://github.com/YunoHost-Apps/ssh_chroot_dir_ynh"
fi

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Check if the app can be installed" --weight=2

# Correct user name
# An unix user name can contains only :alnum: and . - _
# Replace all other characters by _
ssh_user=${ssh_user//[^[:alnum:].\-_]/_}

ynh_system_user_exists $ssh_user && ynh_die "This user already exist"

final_path=/opt/yunohost/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

ynh_print_OFF
if test -z "$password" && test -z "$pub_key"
then
	ynh_die "You can't left empty both password and public key. Please fill at least one of them."
fi
ynh_print_ON

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Store settings from manifest"

ynh_app_setting_set $app ssh_user $ssh_user
ynh_app_setting_set $app size $size

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Download, check and unpack source" --weight=2

ynh_app_setting_set $app final_path $final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path"

#=================================================
# SPECIFIC SETUP
#=================================================
# SOURCE LIBRARIES
#=================================================

# Load functions quotas_xxx
source "$final_path/unix_quotas/unix_quotas.sh"

#=================================================
# CREATE DIRECTORY FOR THIS USER
#=================================================

user_dir="/home/yunohost.app/ssh_chroot_directories/$ssh_user"
mkdir -p "$user_dir"

#=================================================
# INSTALL QUOTAS SYSTEM
#=================================================
ynh_script_progression --message="Install quotas system" --weight=3

# https://github.com/maniackcrudelis/ssh_chroot/blob/master/unix_quotas/unix_quotas.sh
quotas_install

#=================================================
# CONFIGURE FSTAB TO SUPPORT QUOTAS
#=================================================
ynh_script_progression --message="Configure fstab to support quotas" --weight=3

# https://github.com/maniackcrudelis/ssh_chroot/blob/master/unix_quotas/unix_quotas.sh
# Set fstab
quotas_find_mount_point "$user_dir"
quotas_set_fstab "$quotas_mount_point"

# Activate quotas
quotas_activate "$quotas_mount_point"

#=================================================
# CREATE THE USER WITH CHROOT_MANAGER
#=================================================
ynh_script_progression --message="Create the user with Chroot_manager" --weight=5

add_password=""
ynh_print_OFF
if [ -n "$password" ]
then
	auth_opt="--password"
	auth_value="$password"
fi
ynh_print_ON

add_sshkey=""
if [ -n "$pub_key" ]
then
	ynh_app_setting_set $app pub_key $pub_key
	auth_opt="--sshkey"
	auth_value="$pub_key"
fi

ynh_print_OFF
$final_path/chroot_manager.sh adduser --name $ssh_user $auth_opt "$auth_value" --directory "$user_dir" --quota $size
ynh_print_ON

#=================================================
# ADD A LINK TO CHROOT_MANAGER
#=================================================

ln -sf $final_path/chroot_manager.sh /home/yunohost.app/ssh_chroot_directories/chroot_manager

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown -R root: $final_path

#=================================================
# DISCLAIMER
#=================================================

# Get the main domain
domain=$(yunohost domain list | grep -m1 "-" | awk '{print $2}')
ssh_port=$(grep "^Port " /etc/ssh/sshd_config | awk '{print $2}')

ynh_print_info "
To use this directory, connect to 'ssh $ssh_user@$domain -p $ssh_port' via a terminal or by using an sftp connection with 'sftp://$ssh_user@$domain:$ssh_port/data'" >&2

if grep --quiet "^AllowUsers" /etc/ssh/sshd_config
then
	ynh_print_warn "
Be carreful, your ssh configuration contains an AllowUsers option. You should probably add the user $ssh_user to this line."
fi

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

message="A new chrooted directory has been created. To use it, connect to 'ssh $ssh_user@$domain -p $ssh_port' via a terminal or by using an sftp connection with 'sftp://$ssh_user@$domain:$ssh_port/data'

If you're facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/ssh_chroot_dir_ynh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation completed" --last
