#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE QUOTAS OPTIONS IN FSTAB
#=================================================
ynh_script_progression "Remove quotas options in fstab"

# https://github.com/maniackcrudelis/ssh_chroot/blob/master/unix_quotas/unix_quotas.sh
if ! IS_PACKAGE_CHECK; then
    (
        source "$install_dir/unix_quotas/unix_quotas.sh"

        quotas_find_mount_point "$user_dir"
        quotas_clean_fstab "$quotas_mount_point"

        # Deactivate quotas
        quotas_deactivate "$quotas_mount_point"
    )
fi

#=================================================
# REMOVE THE USER WITH CHROOT_MANAGER
#=================================================
ynh_script_progression "Remove the user with Chroot_manager"

if ! IS_PACKAGE_CHECK; then
    "$install_dir/chroot_manager.sh" deluser --name "$ssh_user"
fi

#=================================================
# DISCLAIMER
#=================================================

ynh_print_info "The directory $data_dir hasn't been removed."

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
