#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Checking version..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"
fi

#=================================================
# SOURCE LIBRARIES
#=================================================

# Load functions ssh_chroot_xxx
source "$install_dir/ssh_chroot/ssh_chroot.sh"

#=================================================
# UPDATE THE CHROOT DIRECTORY
#=================================================
ynh_script_progression "Update the chroot directory"

# https://github.com/maniackcrudelis/ssh_chroot/blob/master/ssh_chroot/ssh_chroot.sh
# Build the chroot
ssh_chroot_set_directory "$user_dir"

# Copy some binaries in the chroot
ssh_chroot_standard_binaries "$user_dir"
ssh_chroot_copy_binary rsync "$user_dir"

# Set permissions
if ! IS_PACKAGE_CHECK
then
	ssh_chroot_set_permissions "$user_dir" $ssh_user

	# Allow the user to use ssh
	adduser $ssh_user ssh.app
fi

#=================================================
# UPDATE THE LINK TO CHROOT_MANAGER
#=================================================

ln -sf $install_dir/chroot_manager.sh "$data_dir/chroot_manager"

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R root: $install_dir
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R root: $install_dir
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
