#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

ssh_user=$(ynh_app_setting_get $app ssh_user)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source "$final_path"
fi

#=================================================
# SPECIFIC UPGRADE
#=================================================
# SOURCE LIBRARIES
#=================================================

# Load functions ssh_chroot_xxx
source "$final_path/ssh_chroot/ssh_chroot.sh"

#=================================================
# UPDATE THE CHROOT DIRECTORY
#=================================================

user_dir="/home/yunohost.app/ssh_chroot_directories/$ssh_user"

# https://github.com/maniackcrudelis/ssh_chroot/blob/master/ssh_chroot/ssh_chroot.sh
# Build the chroot
ssh_chroot_set_directory "$user_dir"

# Copy some binaries in the chroot
ssh_chroot_standard_binaries "$user_dir"
ssh_chroot_copy_binary rsync "$user_dir"

# Set permissions
ssh_chroot_set_permissions "$user_dir" $ssh_user

#=================================================
# UPDATE THE LINK TO CHROOT_MANAGER
#=================================================

ln -sf $final_path/chroot_manager.sh /home/yunohost.app/ssh_chroot_directories/chroot_manager

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown -R root: $final_path
